---
- name: Build container with ansible
  hosts: localhost
  tasks:
    - name: stop running container
      command: docker stop first-container
      ignore_errors: yes

    - name: remove stopped container
      command: docker rm -f first-container
      ignore_errors: yes

    - name: remove used image
      command: docker rmi 1st-image
      ignore_errors: yes

    - name: build docker image from dockerfile
      command: docker build -t my-first-image .

    - name: create tag to image
      command: docker tag my-first-image mohamedhmza123/my-first-image:latest

    - name: push image to dockerhub
      command: docker push mohamedhmza123/my-first-image:latest

    - name: run container from image
      command: docker run -d --name first-container -p 8082:80 my-first-image
